remote_theme: daviddarnes/alembic

navigation_header:
  Home: /
  Project 1: /project1/project1.html
  Project 2: /project2/project2.html
  Project 3: /lab6/lab6.html
  Project 4: /project3/project3.html
